"""initial migration

Revision ID: 55a1c50e11be
Revises: 
Create Date: 2026-07-27 11:53:43.425386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a1c50e11be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'descripcion',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('tickets', 'descripcion')
    op.drop_column('tickets', 'titulo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('titulo', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('tickets', sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('roles', 'descripcion',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
